### PR TITLE
initial data dump, file sizes reduced

### PR DESCRIPTION
**Pull request by corinnebosley**
I have:
- reduced the file sizes of all model datasets and then only kept one of each type.
- used slices of aircraft data for scalar and timeseries datasets
- used some CF-incompliant aircraft data as a temporary dataset (to be updated when possible)
- copied some csv files in as obs datasets, but not at reduced file size as I can't load them with iris yet (could do it using xarray or something, but it seems unnecessary at this stage)

### CODE REVIEW

**Comment by bsherratt** [comment]
If anything I would claim they've been cut down too much? At the very least they've been cut down over very uninteresting data.
- `model`: these files have just the bottom left 10x10 cells of a 704x548 grid, which is way out over the sea somewhere. DAQI is a flat 3 at all of those points, and the pollutant concentrations have very little variation. I'd probably choose at least a 50x50 grid, over a city like London. Actually, I would suggest not using a square at all, to make it far more likely that we can identify errors involving getting x and y the wrong way round.
- `aircraft`: the file here has (latitude, longitude, altitude, pressure) measurements every second for 10 seconds. I assume the plane was just taking off, because the last 6 points are just barely over 100m (according to the metadata, the lowest altitude that was considered valid), and the first 4 points are NaN (presumably were below 100m). Pollutant measurements would probably have been more interesting than pressure. And regardless of what was being measured, non-consecutive time points would probably be more interesting (eg the first second of each minute for 10 minutes), and we can probably handle more than 10 of them.
- `timeseries`: exactly as above but for a different 10 seconds, where *all* the data is NaN
- `scalar`: is the first point of the timeseries data, so still NaN

**Comment by corinnebosley** [comment]
@bsherratt I appreciate that you're really thinking about this data, but first of all something just needs to go into this repo.  I don't want to increase the size of the model data because we need something small enough to test really fast.  In fact I think it might still be too big as it is.  And who cares how interesting the data is? It's not for anybody's entertainment, it's just to check that the code works.  I accept that it has to be varied enough to test a variety of circumstances, but there really isn't any need to be so anal about it.  Maybe you could find some more interesting data and make a PR yourself?

I will check and replace the files which are all NaN data, but I strongly resist replacing the rest of the data for something more 'interesting' and I am certainly not increasing the file sizes.

**Comment by corinnebosley** [comment]
@bsherratt I have left the aircraft data exactly as it is, but I have added alternative filtered aircraft data into the timeseries data section, and added all other data in an unsquare fashion.  I have made sure that the data inside the scalar cube is not NaN, but there are still some NaNs left in other data in some places, which is fine as far as I'm concerned.  Means we can use those datasets to test NaNs.

**Comment by bsherratt** [comment]
OK, I see that that didn't come out as helpfully as I hoped.

On "interesting" data, I suppose the advantage I had in mind, but not consciously enough to think to mention it, would be similar to the suggestion on not using a square of data - it would help find bugs. For example if you were expecting the data at indices [3, 5] but the code got data at [4, 6] for some reason, but the values at both points were the same, then an automated test wouldn't be able to flag that as an error. Or when making a plot, it would be easier to notice whether the right thing has been plotted or not if the data is jumping around all over the place, instead of gradually increasing from, say, 55.4 to 55.6. So along those lines, yes it is good to have some NaNs lying around, just not the whole file.

I wasn't convinced that reducing the model data so much would make a significant difference, so I did a quick timing test on simply loading data (`cube = iris.load_cube(...); cube.data`). It was interesting! It seems that if you load something a second time "soon" (no idea how soon) after the first, then it's significantly faster. One day of O3 data for the full UK took about 1.8s from "cold", but 0.19s subsequently. The small corner of O3 data for the same day took 1.2s the first time and then 0.1s. Which *is* definitely faster, but nowhere near proportionate to the relative sizes of the data. That's when I start thinking that if it's not saving much time, the plot might as well show off a bit more than 100 huge grid cells all coloured exactly the same. I don't think I had another actually practical reason to claim this is "not enough" data though, so probably ignore it.

Worth adding that simply importing iris - which of course implies importing a tonne of other dependencies - varied anywhere from about 20-30s. Surely this is the actual bottleneck at the moment, and will continue to be until we have a lot more tests?

I would understand wanting an array small enough that you can kind of reason about it in your head, and which numpy is happy to print in its entirety without ellipses, and you could conceivably dump in actual test code, in which case yes 100 cells is already pushing it. I would also understand concern for git/github and how well they handle large binary files - I imagine not very well, because they're not very compressible. So with further consideration, more for those reasons that filesize itself or the speed of the tests, this data will be fine.

**Comment by lucascatherine** [comment]
Hi Corrine, Sounds great. Thanks for adding these in.

 We will need to add some large data sets later on to test with once we've got the code up and working.  These should then cover the cases you have mentioned Barnaby.

**Comment by lucascatherine** [comment]
Soz, didn't mean to close it ! wrong button !

**Comment by corinnebosley** [comment]
@bsherratt Yes, I apologise for my earlier brashness, I'm feeling a little volatile at the moment and I reacted badly to your comments.  I'll try and act more like a grown-up going forward.

I agree with your point about the data not being square though, so this revised data is all either shaped [5, 4, 3] or [4, 3] and taken from somewhere in the middle of the array so that we can have more non-NaNs.

You are right about the loading speeds, that experiment is interesting and informative.  Yes it would seem that loading iris will be the bottleneck until we have loads of tests, and we will at some point have to put some big data in this repo so that we can do some performance testing, but I see that as a long way down the line yet.

If you're happy with this PR then can I ask you to merge it please?  Otherwise happy to make more changes on your recommendation.

**Pull request merged**
