### PR TITLE
some additions to setup.cfg

### PR DESCRIPTION
**Pull request by corinnebosley**
Changes to settings in "setup.cfg" as described here: https://setuptools.pypa.io/en/latest/userguide/datafiles.html#subdirectory-for-data-files

### CODE REVIEW

**Comment by corinnebosley** [comment]
I'm still not entirely convinced this will work.  I still think it might have been changing hyphens to underscores which broke this.  Best try this out though, just in case.  Works on my machine but I don't know what hidden paths it's already finding without my knowledge.

**Comment by corinnebosley** [comment]
I would be very grateful if @crbunney  could just check that you can download the cap-sample-data package from the latest revision, then import the package and check that it contains files.  Then if that's the case I will ask for your review and merge if you approve.

**Comment by corinnebosley** [comment]
NOTE: @crbunney I am just holding off this one (despite passing tests) because I want to merge cap-sample-data changes first, then change the URL in `tox.ini` and `environment.yaml` here to reflect the main cap-sample-data codebase.

**Comment by corinnebosley** [comment]
@crbunney I wondered about that myself, so here is the package without the setup.py.  If you could test this for me on your clean machine that'd be great.  Thanks!

**Review by crbunney — APPROVED** [review]
All good and working 👍🏻

**Comment by corinnebosley** [comment]
Yayyy! I'm gonna merge it. I'm so excited!!

**Pull request merged**
