### PR TITLE
changed hyphens to underscores in setup.cfg

### PR DESCRIPTION
**Pull request by corinnebosley**

### CODE REVIEW

**Comment by corinnebosley** [comment]
Seems to build and install fine in my own cap_env.  Hopefully this will help tests run in cap.

**Review by crbunney — APPROVED** [review]
Tested with:
```bash
# Setup test env
conda create --name pr_test python=3.8 pip
conda activate pr_test

# Install package
pip install https://github.com/ADAQ-AQI/cap-sample-data/archive/make_package.zip

# Validate installation
python -c "import cap_sample_data; print(cap_sample_data.path)"

# Clean up
conda deactivate
conda remove --name pr_test --all -y
```

All looks good to me, package installed and importable, it printed out the path as expected.

So good to go 👍🏻

**Comment by corinnebosley** [comment]
That setup.cfg does look a lot tidier now.  Thanks for the help.

**Comment by corinnebosley** [comment]
@crbunney I am happy to merge this now if you think it's ok?

**Comment by crbunney** [comment]
> @crbunney I am happy to merge this now if you think it's ok?

Yep, all good

**Pull request merged**
