### PR TITLE
added pyproject.toml from example file.

### PR DESCRIPTION
**Pull request by corinnebosley**
I don't know much about these files, but I have done my best to tailor this one to the sample data repo, leaving some placeholders in there in case we want to use them later.

If you get the time, a review and a merge would be great, otherwise no worries, I'll get back on it when I'm better.

### CODE REVIEW

**Review by crbunney — COMMENTED** [review]
Looks fine to me, although I'm not sure why it's being added?

**Comment by lucascatherine** [comment]
Hi Corrinne, seems fine. Is this so we can set up a pip install for clean_air ?

**Comment by corinnebosley** [comment]
Yes, the purpose of this is so that we can pip- or conda-install cap-sample-data and then use it in demo notebooks.  I could probably use the PYTHONPATH variable instead, but that doesn't seem like a sustainable or reuseable method.

**Review by crbunney — APPROVED** [review]
Oh yea, pip installable is definitely better than managing `PYTHONPATH` additions. I had a feeling that it may need a `setup.cfg` in addition to the `pyproject.toml`, but if pip can install it without without a `setup.cfg` by using some kind of default values, then I'm happy

**Comment by corinnebosley** [comment]
I have to admit, I haven't tested it yet, and you may well be correct in the requirement of a` setup.cfg`.

I shall create one of those (`setup.cfg`), test it if I can and then push this again.  Thanks.

**Comment by corinnebosley** [comment]
I have been having a bit of trouble figuring out how to construct a setup.cfg (there's a lot of available options, and I don't know the right answers to many of them), so I have emailed AVD to see if they can help me out with this.  Waiting on a response, with not a huge amount of hope as they seem very busy and understaffed at the moment, just like the rest of us.

**Comment by corinnebosley** [comment]
@lucascatherine I noticed that Barnaby had already added a setup.cfg to clean_air, so I used that as a template and modified it for cap-sample-data.  Tested the pip install and it worked fine, so if you can approve this PR then we can merge it and have some working setup files in our sample data repo.

**Comment by lucascatherine** [comment]
Looks all good to me.  I'll approve now.

**Comment by corinnebosley** [comment]
Yayyy! Thanks Catherine.

**Pull request merged**
